server:
  port: 8014

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shokify_order   # Change port for each service
    username: root
    password: Kamrul14!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  config:
    customer-url: http://localhost:8222/api/v1/user
    payment-url: http://localhost:8222/api/v1/inventory
    product-url: http://localhost:8222/api/v1/products