server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shokify_product   # Change port for each service
    username: root
    password: Kamrul14!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
