name: environment-workflow

on:
  push:

jobs:
  setup-and-init-db:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Kamrul14!
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -pKamrul14! --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy python-dotenv mysql-connector-python

    - name: Make init.sh executable
      run: chmod +x ./init.sh

    - name: Run init.sh to initialize database
      env:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: Kamrul14!
        MYSQL_HOST: 127.0.0.1
      run: ./init.sh
